// Copyright (c) 2023-present Mattermost, Inc. All Rights Reserved.
// See LICENSE.txt for license information.

package llm

// Automatically generated convenience vars for the filenames in llm/prompts/
const (
	PromptAttendanceConfirmationAnalysis       = "attendance_confirmation_analysis"
	PromptAttendanceConfirmationGeneration     = "attendance_confirmation_generation"
	PromptAttendanceReasonAnalysis             = "attendance_reason_analysis"
	PromptAttendanceUnifiedAnalysis            = "attendance_unified_analysis"
	PromptComprehensiveModificationAnalysis    = "comprehensive_modification_analysis"
	PromptDirectMessageQuestionSystem          = "direct_message_question_system"
	PromptEmojiSelectSystem                    = "emoji_select_system"
	PromptEmployeeDisambiguationAnalysis       = "employee_disambiguation_analysis"
	PromptErpActionClassification              = "erp_action_classification"
	PromptErpModuleClassification              = "erp_module_classification"
	PromptExistingEntityDisambiguationAnalysis = "existing_entity_disambiguation_analysis"
	PromptFindActionItemsSystem                = "find_action_items_system"
	PromptFindActionItemsUser                  = "find_action_items_user"
	PromptFindOpenQuestionsSystem              = "find_open_questions_system"
	PromptFindOpenQuestionsUser                = "find_open_questions_user"
	PromptGeneralKnowledgeResponse             = "general_knowledge_response"
	PromptLocale                               = "locale"
	PromptMeetingSummaryGeneral                = "meeting_summary_general"
	PromptMeetingSummarySystem                 = "meeting_summary_system"
	PromptMeetingSummaryUser                   = "meeting_summary_user"
	PromptProjectConfirmationGeneration        = "project_confirmation_generation"
	PromptProjectCreationAnalysis              = "project_creation_analysis"
	PromptProjectModificationAnalysis          = "project_modification_analysis"
	PromptProjectSelectionAnalysis             = "project_selection_analysis"
	PromptSearchResults                        = "search_results"
	PromptSearchSystem                         = "search_system"
	PromptSearchUser                           = "search_user"
	PromptStandardPersonality                  = "standard_personality"
	PromptStandardPersonalityWithoutLocale     = "standard_personality_without_locale"
	PromptSummarizeChannelRangeSystem          = "summarize_channel_range_system"
	PromptSummarizeChannelSinceSystem          = "summarize_channel_since_system"
	PromptSummarizeChunkSystem                 = "summarize_chunk_system"
	PromptSummarizeThreadSystem                = "summarize_thread_system"
	PromptTaskConfirmationGeneration           = "task_confirmation_generation"
	PromptTaskCreationAnalysis                 = "task_creation_analysis"
	PromptTaskModificationAnalysis             = "task_modification_analysis"
	PromptThreadUser                           = "thread_user"
)
